import { Inter } from "next/font/google";
import Clock from "./components/clock";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Good afternoon, Riley</h1>
        <h3 id="time">Monday 8th May</h3>
        <div className="outer">
          <div className="container">
            <Clock />
          </div>
          <div className="container">
            <input type="search" name="" id="" />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
