'Imports':
    'BmToCsv': 'python\components\browser_bookmarks_to_csv.py'  # Bookmark Python File Location
    'NtToCsv': 'python\components\nighttabjson_to_csv.py'       # NightTab Py File Location
    'UneditedFolder': 'python\original'     # Unedited / Uploaded Paths
    'EditedFolder': 'python\processed'      # Edited / Uploaded files go to when they converted to csv

'Unedited':
    'BookmarkFile': 'bookmarks'
    'NightTabFile': 'nightTab'

'Edited':
    'output': 'output'

'Css':
    'White': 'edf2f3'
    'WhiteSec': 'c4d7db'
    'Black': '1a2224'
    'BlackSec': '3b494d'

'Subjects':
    'athematics': '0000FF'           # Blue
    'Geography': '228B22'            # Forest Green
    'Physics': '800080'              # Purple
    'Biology': '1E90FF'              # Dodger Blue
    'Chemistry': '008000'            # Green
    'Psychology': 'D8BFD8'           # Thistle
    'ComputerScience': '006400'      # Dark Green
    'Philosophy': 'F5DEB3'           # Wheat
    'English': 'FFFF00'              # Yellow
    'Engineering': 'FFD700'          # Gold